// <auto-generated />
using HuntOps.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HuntOps.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HuntOpsDbContext))]
    [Migration("20261004210034_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HuntOps.Domain.Operations.WorkerHeartbeat", b =>
                {
                    b.Property<string>("WorkerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("worker_id");

                    b.Property<string>("Component")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("component");

                    b.Property<Instant>("LastBeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_beat_at");

                    b.Property<Instant>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Version")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("version");

                    b.HasKey("WorkerId", "Component")
                        .HasName("pk_worker_heartbeats");

                    b.ToTable("worker_heartbeats", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
