// <auto-generated />
using System;
using HuntOps.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HuntOps.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HuntOpsDbContext))]
    partial class HuntOpsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HuntOps.Domain.Access.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<Instant?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("hash");

                    b.Property<Instant?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("prefix");

                    b.Property<Instant?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<int>("Scopes")
                        .HasColumnType("integer")
                        .HasColumnName("scopes");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_api_keys");

                    b.HasIndex("Prefix")
                        .IsUnique()
                        .HasDatabaseName("ix_api_keys_prefix");

                    b.ToTable("api_keys", null, t =>
                        {
                            t.HasCheckConstraint("ck_api_keys_hash_sha256", "octet_length(hash) = 32");

                            t.HasCheckConstraint("ck_api_keys_prefix_format", "prefix ~ '^hops_[a-z0-9]{8}$'");

                            t.HasCheckConstraint("ck_api_keys_scopes", "scopes BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("HuntOps.Domain.Actions.ActionStatusChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("changed_by");

                    b.Property<string>("ChangedVia")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("changed_via");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note");

                    b.Property<string>("Outcome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("outcome");

                    b.Property<Guid>("RequiredActionId")
                        .HasColumnType("uuid")
                        .HasColumnName("required_action_id");

                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Sequence"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_action_status_changes");

                    b.HasIndex("Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_action_status_changes_sequence");

                    b.HasIndex("RequiredActionId", "UserId", "ChangedAt")
                        .HasDatabaseName("ix_action_status_changes_required_action_id_user_id_changed_at");

                    b.ToTable("action_status_changes", null, t =>
                        {
                            t.HasCheckConstraint("ck_action_status_changes_changed_via", "changed_via IN ('Web', 'Api', 'Mcp', 'Notification', 'Cli', 'System')");

                            t.HasCheckConstraint("ck_action_status_changes_status", "status IN ('Completed', 'NotApplicable', 'Cancelled', 'Reopened')");
                        });
                });

            modelBuilder.Entity("HuntOps.Domain.Actions.RequiredAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("boolean")
                        .HasColumnName("is_optional");

                    b.Property<string>("Kind")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("kind");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("ProgramEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_event_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_required_actions");

                    b.HasIndex("ProgramEventId")
                        .HasDatabaseName("ix_required_actions_program_event_id");

                    b.ToTable("required_actions", null, t =>
                        {
                            t.HasCheckConstraint("ck_required_actions_title_not_blank", "length(btrim(title)) > 0");
                        });
                });

            modelBuilder.Entity("HuntOps.Domain.Events.EventType", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<Instant?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultActionTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("default_action_title");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<bool>("IsWindowByDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_window_by_default");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Key")
                        .HasName("pk_event_types");

                    b.ToTable("event_types", null, t =>
                        {
                            t.HasCheckConstraint("ck_event_types_category", "category IN ('Application', 'Purchase', 'Results', 'Reporting', 'Season', 'Other')");

                            t.HasCheckConstraint("ck_event_types_key_format", "key ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");
                        });

                    b.HasData(
                        new
                        {
                            Key = "application-period",
                            Category = "Application",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17910720000000000L),
                            DefaultActionTitle = "Submit application",
                            Description = "Window during which draw or permit applications are accepted.",
                            DisplayName = "Application period",
                            IsSystem = true,
                            IsWindowByDefault = true,
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17910720000000000L),
                            Version = 0u
                        },
                        new
                        {
                            Key = "preference-point-period",
                            Category = "Purchase",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17910720000000000L),
                            DefaultActionTitle = "Purchase preference point",
                            Description = "Window for buying a preference or bonus point without applying for a tag.",
                            DisplayName = "Preference/bonus point purchase",
                            IsSystem = true,
                            IsWindowByDefault = true,
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17910720000000000L),
                            Version = 0u
                        },
                        new
                        {
                            Key = "license-purchase",
                            Category = "Purchase",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17910720000000000L),
                            DefaultActionTitle = "Purchase license or tag",
                            Description = "Window for purchasing a license, tag or permit that was drawn or is otherwise available.",
                            DisplayName = "License or tag purchase",
                            IsSystem = true,
                            IsWindowByDefault = true,
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17910720000000000L),
                            Version = 0u
                        },
                        new
                        {
                            Key = "otc-sale",
                            Category = "Purchase",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17910720000000000L),
                            DefaultActionTitle = "Purchase OTC tag",
                            Description = "Date over-the-counter licenses or tags go on sale.",
                            DisplayName = "Over-the-counter sale",
                            IsSystem = true,
                            IsWindowByDefault = false,
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17910720000000000L),
                            Version = 0u
                        },
                        new
                        {
                            Key = "leftover-sale",
                            Category = "Purchase",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17910720000000000L),
                            DefaultActionTitle = "Purchase leftover tag",
                            Description = "Sale or draw of leftover, returned or reissued tags.",
                            DisplayName = "Leftover or reissue sale",
                            IsSystem = true,
                            IsWindowByDefault = false,
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17910720000000000L),
                            Version = 0u
                        },
                        new
                        {
                            Key = "draw-results",
                            Category = "Results",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17910720000000000L),
                            Description = "Date draw results are expected to be published.",
                            DisplayName = "Draw results",
                            IsSystem = true,
                            IsWindowByDefault = false,
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17910720000000000L),
                            Version = 0u
                        },
                        new
                        {
                            Key = "application-withdrawal",
                            Category = "Application",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17910720000000000L),
                            Description = "Last day to withdraw an application, surrender a tag or request a refund.",
                            DisplayName = "Application withdrawal or refund deadline",
                            IsSystem = true,
                            IsWindowByDefault = false,
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17910720000000000L),
                            Version = 0u
                        },
                        new
                        {
                            Key = "harvest-reporting",
                            Category = "Reporting",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17910720000000000L),
                            DefaultActionTitle = "Submit harvest report",
                            Description = "Period during which mandatory harvest or survey reports must be submitted.",
                            DisplayName = "Harvest reporting",
                            IsSystem = true,
                            IsWindowByDefault = true,
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17910720000000000L),
                            Version = 0u
                        },
                        new
                        {
                            Key = "season",
                            Category = "Season",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17910720000000000L),
                            Description = "Hunting season dates.",
                            DisplayName = "Season",
                            IsSystem = true,
                            IsWindowByDefault = true,
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17910720000000000L),
                            Version = 0u
                        },
                        new
                        {
                            Key = "other",
                            Category = "Other",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17910720000000000L),
                            Description = "Any other dated item worth tracking.",
                            DisplayName = "Other",
                            IsSystem = true,
                            IsWindowByDefault = false,
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17910720000000000L),
                            Version = 0u
                        });
                });

            modelBuilder.Entity("HuntOps.Domain.Events.ProgramEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<LocalDate?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<LocalTime?>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<Instant?>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at_utc");

                    b.Property<string>("EventTypeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type_key");

                    b.Property<string>("ExternalKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_key");

                    b.Property<Instant?>("LastSourceConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_source_confirmed_at");

                    b.Property<Instant?>("LastVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_verified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("OriginKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("origin_kind");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<string>("Qualifier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("")
                        .HasColumnName("qualifier");

                    b.Property<string>("SeasonLabel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("season_label");

                    b.Property<int>("SeasonYear")
                        .HasColumnType("integer")
                        .HasColumnName("season_year");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("source_url");

                    b.Property<LocalDate>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<LocalTime?>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<Instant>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("verification_status");

                    b.Property<string>("VerifiedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("verified_by");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_program_events");

                    b.HasIndex("EndsAtUtc")
                        .HasDatabaseName("ix_program_events_ends_at_utc");

                    b.HasIndex("EventTypeKey")
                        .HasDatabaseName("ix_program_events_event_type_key");

                    b.HasIndex("StartsAtUtc")
                        .HasDatabaseName("ix_program_events_starts_at_utc");

                    b.HasIndex("ProgramId", "SeasonYear", "EventTypeKey", "Qualifier")
                        .IsUnique()
                        .HasDatabaseName("ux_program_events_natural_key_active")
                        .HasFilter("archived_at IS NULL");

                    b.ToTable("program_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_program_events_end_after_start", "ends_at_utc IS NULL OR ends_at_utc >= starts_at_utc");

                            t.HasCheckConstraint("ck_program_events_end_after_start_date", "end_date IS NULL OR end_date >= start_date");

                            t.HasCheckConstraint("ck_program_events_end_time_needs_end_date", "end_time IS NULL OR end_date IS NOT NULL");

                            t.HasCheckConstraint("ck_program_events_name_not_blank", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_program_events_origin_kind", "origin_kind IN ('Manual', 'Import', 'Source', 'Mcp')");

                            t.HasCheckConstraint("ck_program_events_season_year", "season_year BETWEEN 1900 AND 2200");

                            t.HasCheckConstraint("ck_program_events_verification_status", "verification_status IN ('Unverified', 'Verified')");

                            t.HasCheckConstraint("ck_program_events_window_instants", "(end_date IS NULL) = (ends_at_utc IS NULL)");
                        });
                });

            modelBuilder.Entity("HuntOps.Domain.Operations.WorkerHeartbeat", b =>
                {
                    b.Property<string>("WorkerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("worker_id");

                    b.Property<string>("Component")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("component");

                    b.Property<Instant>("LastBeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_beat_at");

                    b.Property<Instant>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Version")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("version");

                    b.HasKey("WorkerId", "Component")
                        .HasName("pk_worker_heartbeats");

                    b.ToTable("worker_heartbeats", (string)null);
                });

            modelBuilder.Entity("HuntOps.Domain.Reference.Agency", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("abbreviation");

                    b.Property<Instant?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("JurisdictionId")
                        .HasColumnType("uuid")
                        .HasColumnName("jurisdiction_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_key");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("website_url");

                    b.HasKey("Id")
                        .HasName("pk_agencies");

                    b.HasIndex("JurisdictionId", "NameKey")
                        .IsUnique()
                        .HasDatabaseName("ux_agencies_jurisdiction_name_active")
                        .HasFilter("archived_at IS NULL");

                    b.ToTable("agencies", null, t =>
                        {
                            t.HasCheckConstraint("ck_agencies_name_not_blank", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("HuntOps.Domain.Reference.HuntProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<Instant?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Method")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("method");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_key");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<Guid?>("ParentProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_program_id");

                    b.Property<string>("PermitType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permit_type");

                    b.Property<string>("Residency")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("residency");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<string>("Species")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("species");

                    b.Property<string>("Unit")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("unit");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("website_url");

                    b.HasKey("Id")
                        .HasName("pk_programs");

                    b.HasIndex("ParentProgramId")
                        .HasDatabaseName("ix_programs_parent_program_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_programs_slug_active")
                        .HasFilter("archived_at IS NULL");

                    b.HasIndex("Species")
                        .HasDatabaseName("ix_programs_species");

                    b.HasIndex("AgencyId", "NameKey")
                        .IsUnique()
                        .HasDatabaseName("ux_programs_agency_name_active")
                        .HasFilter("archived_at IS NULL");

                    b.ToTable("programs", null, t =>
                        {
                            t.HasCheckConstraint("ck_programs_name_not_blank", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_programs_not_own_parent", "parent_program_id IS NULL OR parent_program_id <> id");

                            t.HasCheckConstraint("ck_programs_slug_format", "slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");
                        });
                });

            modelBuilder.Entity("HuntOps.Domain.Reference.Jurisdiction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_key");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("website_url");

                    b.HasKey("Id")
                        .HasName("pk_jurisdictions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_jurisdictions_code_active")
                        .HasFilter("archived_at IS NULL");

                    b.HasIndex("NameKey")
                        .IsUnique()
                        .HasDatabaseName("ux_jurisdictions_name_active")
                        .HasFilter("archived_at IS NULL");

                    b.ToTable("jurisdictions", null, t =>
                        {
                            t.HasCheckConstraint("ck_jurisdictions_code_upper", "code = upper(code) AND length(code) BETWEEN 1 AND 10");

                            t.HasCheckConstraint("ck_jurisdictions_country", "country ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_jurisdictions_name_not_blank", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("HuntOps.Domain.Users.OwnerSettings", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("user_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("QuietHoursEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("quiet_hours_enabled");

                    b.Property<LocalTime>("QuietHoursEnd")
                        .HasColumnType("time")
                        .HasColumnName("quiet_hours_end");

                    b.Property<LocalTime>("QuietHoursStart")
                        .HasColumnType("time")
                        .HasColumnName("quiet_hours_start");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("UrgentBypassesQuietHours")
                        .HasColumnType("boolean")
                        .HasColumnName("urgent_bypasses_quiet_hours");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("UserId")
                        .HasName("pk_owner_settings");

                    b.ToTable("owner_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_owner_settings_quiet_hours_distinct", "quiet_hours_start <> quiet_hours_end");
                        });
                });

            modelBuilder.Entity("HuntOps.Infrastructure.Identity.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_owner");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("IsOwner")
                        .IsUnique()
                        .HasDatabaseName("ux_users_single_owner")
                        .HasFilter("is_owner");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("HuntOps.Domain.Actions.ActionStatusChange", b =>
                {
                    b.HasOne("HuntOps.Domain.Actions.RequiredAction", "RequiredAction")
                        .WithMany()
                        .HasForeignKey("RequiredActionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_action_status_changes_required_actions_required_action_id");

                    b.Navigation("RequiredAction");
                });

            modelBuilder.Entity("HuntOps.Domain.Actions.RequiredAction", b =>
                {
                    b.HasOne("HuntOps.Domain.Events.ProgramEvent", "ProgramEvent")
                        .WithMany("Actions")
                        .HasForeignKey("ProgramEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_required_actions_program_events_program_event_id");

                    b.Navigation("ProgramEvent");
                });

            modelBuilder.Entity("HuntOps.Domain.Events.ProgramEvent", b =>
                {
                    b.HasOne("HuntOps.Domain.Events.EventType", "EventType")
                        .WithMany()
                        .HasForeignKey("EventTypeKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_program_events_event_types_event_type_key");

                    b.HasOne("HuntOps.Domain.Reference.HuntProgram", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_program_events_programs_program_id");

                    b.Navigation("EventType");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("HuntOps.Domain.Reference.Agency", b =>
                {
                    b.HasOne("HuntOps.Domain.Reference.Jurisdiction", "Jurisdiction")
                        .WithMany("Agencies")
                        .HasForeignKey("JurisdictionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_agencies_jurisdictions_jurisdiction_id");

                    b.Navigation("Jurisdiction");
                });

            modelBuilder.Entity("HuntOps.Domain.Reference.HuntProgram", b =>
                {
                    b.HasOne("HuntOps.Domain.Reference.Agency", "Agency")
                        .WithMany("Programs")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_programs_agencies_agency_id");

                    b.HasOne("HuntOps.Domain.Reference.HuntProgram", "ParentProgram")
                        .WithMany()
                        .HasForeignKey("ParentProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_programs_programs_parent_program_id");

                    b.Navigation("Agency");

                    b.Navigation("ParentProgram");
                });

            modelBuilder.Entity("HuntOps.Domain.Users.OwnerSettings", b =>
                {
                    b.HasOne("HuntOps.Infrastructure.Identity.AppUser", null)
                        .WithOne()
                        .HasForeignKey("HuntOps.Domain.Users.OwnerSettings", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_owner_settings_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HuntOps.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HuntOps.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("HuntOps.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HuntOps.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });

            modelBuilder.Entity("HuntOps.Domain.Events.ProgramEvent", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("HuntOps.Domain.Reference.Agency", b =>
                {
                    b.Navigation("Programs");
                });

            modelBuilder.Entity("HuntOps.Domain.Reference.Jurisdiction", b =>
                {
                    b.Navigation("Agencies");
                });
#pragma warning restore 612, 618
        }
    }
}
